repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      # Run the formatter.
      - id: ruff-format
        #args: [ --diff]
        types_or: [python, pyi]
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: ["--fix","--config","backend/pyproject.toml"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.9
    hooks:
      # Update the uv lockfile
      - id: uv-lock
        files: backend/uv.lock
        args: ["--project", "backend/pyproject.toml"]
