FROM python:3.12-slim

# ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /linter

RUN pip install --no-cache-dir pre-commit

RUN git init

COPY uv.lock pyproject.toml ./
COPY *.py ./
COPY .pre-commit-config.yaml .

COPY pre-commit-entry.sh ./pre-commit-entry.sh
RUN chmod +x ./pre-commit-entry.sh

# RUN git add *.py
# RUN git status

ENTRYPOINT ["./pre-commit-entry.sh"]
# CMD ["sh", "-c", "pre-commit run --all-files --verbose || true && tail -f /dev/null"]
# CMD ["sh", "-c", " tail -f /dev/null"]
# CMD ["pre-commit", "run", "--all-files"]
#CMD ["sh", "-c", "pwd && ls -la &&  ls -la .venv/bin && tail -f /dev/null"]